name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # running a seperate job on each due to artifact output name difference
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - uses: msys2/setup-msys2@v2
      with:
        pacboy: >-
          gcc:i
          make:i
          alure:i
          freealut:i

    - name: Setup Allegro4 Build
      working-directory: lib/allegro4
      run: mkdir Build

    - run: |
        get-command gcc.exe
        get-command g++.exe
        get-command ld.exe
        get-command mingw32-make.exe
        get-command nm.exe

    - name: Allegro4 CMake
      working-directory: lib/allegro4/Build
      run: >-
        cmake -Wno-dev
        -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo"
        -DCMAKE_C_COMPILER:FILEPATH="gcc.exe"
        -DCMAKE_COLOR_MAKEFILE:BOOL="0"
        -DCMAKE_CXX_COMPILER:STRING="g++.exe"
        -DCMAKE_LINKER:FILEPATH="ld.exe"
        -DCMAKE_MAKE_PROGRAM:FILEPATH="mingw32-make.exe"
        -DCMAKE_NM:FILEPATH="nm.exe"
        -DDDRAW_INCLUDE_DIR:PATH="../dx80_mgw/include"
        -DDDRAW_LIBRARY:FILEPATH="../dx80_mgw/lib/libddraw.a"
        -DDINPUT_INCLUDE_DIR:PATH="../dx80_mgw/include"
        -DDINPUT_LIBRARY:FILEPATH="../dx80_mgw/lib/libdinput.a"
        -DDSOUND_INCLUDE_DIR:PATH="../dx80_mgw/include"
        -DDSOUND_LIBRARY:FILEPATH="../dx80_mgw/lib/libdsound.a"
        -DDXGUID_LIBRARY:FILEPATH="../dx80_mgw/lib/libdxguid.a"
        -DSHARED:BOOL="1"
        -DWANT_ALLEGROGL:BOOL="0"
        -DWANT_DOCS:BOOL="0"
        -DWANT_EXAMPLES:BOOL="0"
        -DWANT_JPGALLEG:BOOL="0"
        -DWANT_LOADPNG:BOOL="0"
        -DWANT_LOGG:BOOL="0"
        -DWANT_MODULES:BOOL="0"
        -DWANT_TESTS:BOOL="0"
        -DWANT_TOOLS:BOOL="0"
        -DWANT_X11:BOOL="0"
        -G "MinGW Makefiles"
        ..

    - name: Allegro4 make
      working-directory: lib/allegro4/Build
      run: mingw32-make.exe

    - name: make
      run: mingw32-make.exe

    - name: Upload Build
      uses: actions/upload-artifact@v5.0.0
      with:
        name: Atomulator-windows
        path: bin/Atomulator.exe

  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install deps
      run: sudo apt install -y libalut-dev liballegro4-dev

    - name: make
      run: make all

    - name: Upload Build
      uses: actions/upload-artifact@v5.0.0
      with:
        name: Atomulator-linux
        path: bin/Atomulator
