name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # running a seperate job on each due to artifact output name difference
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    env:
      BUILD_TOOL_BIN: C:/mingw32/bin
      INCLUDE: C:/mingw32/include

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Setup Allegro4 Build
      working-directory: lib/allegro4
      run: mkdir Build

    - name: Cache Allegro4 Cmake
      id: cache-allegro4
      uses: actions/cache@v4
      with:
        path: lib/allegro4/Build
        key: ${{ runner.os }}-allegro4

    - name: Allegro4 CMake
      if: steps.cache-allegro4.outputs.cache-hit != 'true'
      working-directory: lib/allegro4/Build
      run: |
        $env:Path = "$env:BUILD_TOOL_BIN;" + $env:Path
        cmake -Wno-dev `
        -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" `
        -DCMAKE_COLOR_MAKEFILE:BOOL="0" `
        -DCMAKE_C_COMPILER:FILEPATH="gcc.exe" `
        -DCMAKE_CXX_COMPILER:STRING="g++.exe" `
        -DCMAKE_LINKER:FILEPATH="ld.exe" `
        -DCMAKE_MAKE_PROGRAM:FILEPATH="mingw32-make.exe" `
        -DCMAKE_NM:FILEPATH="nm.exe" `
        -DDDRAW_INCLUDE_DIR:PATH="$env:GITHUB_WORKSPACE/lib/dx80_mgw/include" `
        -DDDRAW_LIBRARY:FILEPATH="$env:GITHUB_WORKSPACE/lib/dx80_mgw/lib/libddraw.a" `
        -DDINPUT_INCLUDE_DIR:PATH="$env:GITHUB_WORKSPACE/lib/dx80_mgw/include" `
        -DDINPUT_LIBRARY:FILEPATH="$env:GITHUB_WORKSPACE/lib/dx80_mgw/lib/libdinput.a" `
        -DDSOUND_INCLUDE_DIR:PATH="$env:GITHUB_WORKSPACE/lib/dx80_mgw/include" `
        -DDSOUND_LIBRARY:FILEPATH="$env:GITHUB_WORKSPACE/lib/dx80_mgw/lib/libdsound.a" `
        -DDXGUID_LIBRARY:FILEPATH="$env:GITHUB_WORKSPACE/lib/dx80_mgw/lib/libdxguid.a" `
        -DSHARED:BOOL="1" `
        -DWANT_ALLEGROGL:BOOL="0" `
        -DWANT_DOCS:BOOL="0" `
        -DWANT_EXAMPLES:BOOL="0" `
        -DWANT_JPGALLEG:BOOL="0" `
        -DWANT_LOADPNG:BOOL="0" `
        -DWANT_LOGG:BOOL="0" `
        -DWANT_MODULES:BOOL="0" `
        -DWANT_TESTS:BOOL="0" `
        -DWANT_TOOLS:BOOL="0" `
        -DWANT_X11:BOOL="0" `
        -G "MinGW Makefiles" `
        ..
        mingw32-make.exe

    - name: Cache OpenAL CMake
      id: cache-openal
      uses: actions/cache@v4
      with:
        path: lib/openal-soft/build
        key: ${{ runner.os }}-openal

    - name: OpenAL Make & Build
      if: steps.cache-openal.outputs.cache-hit != 'true'
      working-directory: lib/openal-soft/build
      run: |
        $env:Path = "$env:BUILD_TOOL_BIN;" + $env:Path
        cmake ..
        cmake --build .

    - name: make Atomulator
      run: |
        $env:Path = "$env:BUILD_TOOL_BIN;" + $env:Path
        mingw32-make.exe all

    - name: Copy DLLs
      run:
        ls lib/allegro4/Build/lib
        ls lib/openal-soft/build/lib
        cp lib/allegro4/Build/lib/*.dll bin
        cp lib/openal-soft/build/lib/*.dll bin

    - name: Upload Build
      uses: actions/upload-artifact@v5.0.0
      with:
        name: Atomulator-windows
        path: bin

  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install deps
      run: sudo apt install -y libalut-dev liballegro4-dev

    - name: make
      run: make all

    - name: Upload Build
      uses: actions/upload-artifact@v5.0.0
      with:
        name: Atomulator-linux
        path: bin/Atomulator
